#!/bin/sh
#
# Must be run as root
#
# Get the system ready for a snapshot on the web dashboard
#
# You need to have these files in the dirac $HOME directory first!
#   hostcert.pem 
#   hostkey.pem
#   yandex-wn-setup
#   yandex-wn-dirac-setup
#   yandex-wn-dirac-run
# 

# Catch up as much as we can before the snapshot
yum -y update 

# Our script is run at the end of boot up
echo '/home/dirac/yandex-wn-setup' >>/etc/rc.d/rc.local

# Rather than just do this to you!
echo 'Now execute   shutdown -h now'
