#!/bin/sh -x
#
# Runs as dirac. Sets up to run dirac-pilot.py
#

date 
export HOST=`/bin/hostname`
export HOME=/home/dirac
mkdir -p $HOME/$1
cd $HOME/$1

DIRAC_SITE=CLOUD.YANDEX.ru
LHCBDIRAC_SETUP=LHCb-Production
CE_NAME=cloud.yandex.ru

export LHCBDIRAC_TMPDIR=`mktemp -d -p $DIRAC_TMP`
cd $LHCBDIRAC_TMPDIR

# Default if not given explicitly
LHCBDIRAC_SETUP=LHCb-Production

# JOB_ID is used by when reporting LocalJobID by DIRAC watchdog
export JOB_ID=$HOST

# We might be running from cvmfs or from /var/spool/checkout
export CONTEXTDIR=`readlink -f \`dirname $0\``

export TMPDIR=$LHCBDIRAC_TMPDIR
export EDG_WL_SCRATCH=$TMPDIR

# Needed to find software area
export VO_LHCB_SW_DIR=/cvmfs/lhcb.cern.ch

# Concatenated full certificate and key
export X509_USER_PROXY=$HOME/etc/grid-security/x509proxy.pem

python $HOME/production/Pilot3/dirac-pilot.py \
 --debug \
 --setup=$LHCBDIRAC_SETUP \
 --pilotCFGFile=$HOME/production/Pilot3/pilot.json \
 -l LHCb \
 -o lbRunOnly \
 --Name=$CE_NAME \
 --Queue=default \
 --MaxCycles=1 \
 --name=$DIRAC_SITE \
 --cert \
 --certLocation=$HOME/etc/grid-security \
 --commandExtensions LHCbPilot \
 --pythonVersion=3

