#!/bin/sh
#
# Setup commands which must be run as root (from /etc/rc.d/rc.local)
#

set -vx

if [ -f /var/lock/subsys/yandex-wn-setup ] ; then
  exit
fi

touch /var/lock/subsys/yandex-wn-setup

(
date
printenv

export HOME=/root
setenforce 0
yum -y install epel-release
yum -y install yum-priorities
yum -y install http://repository.egi.eu/sw/production/umd/4/centos7/x86_64/updates/umd-release-4.1.3-1.el7.centos.noarch.rpm
yum -y update
yum -y install curl wget joe cvmfs cvmfs-config-egi glibc glibc-headers

# Install the Yandex CLI
curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
if [ -r /root/yandex-cloud/path.bash.inc ] ; then
. /root/yandex-cloud/path.bash.inc
fi

# Only root needs this
mv -f /home/lhcb/yandex-oauth.txt /root/yandex-oauth.txt
chown root.root /root/yandex-oauth.txt

# Get list of internal IP addresses of the Squids' instance group
# The Cloud ID and Folder ID will need to be updated if they change!
yc compute instance-group list-instances \
 --cloud-id b1g54dbp1scvqlrhgdns \
 --folder-id b1g6qvo98t320vf133hm \
 --token `cat /root/yandex-oauth.txt` \
 --name lhcb-squid-prod \
 | cut -d'|' -f5 \
 | grep '^ [1-9]' \
 | head -5 \
 | sed 's/ *//g' \
 | sed 's,.*,http://&:3128,' >/root/proxy-urls.txt

echo List of Squid cache internal IPs
cat /root/proxy-urls.txt

# Make the list into a CVMFS proxy expression
echo CVMFS_HTTP_PROXY='"'`cat /root/proxy-urls.txt`'"' \
 | sed 's/ /|/g' >>/etc/cvmfs/default.conf

echo '/cvmfs program:/etc/auto.cvmfs' >>/etc/auto.master
systemctl restart autofs

# Check if cvmfs is working
ls /cvmfs/grid.cern.ch /cvmfs/lhcb.cern.ch

# We never let VMs send emails (likely to be annoying errors from root)
/sbin/iptables -A OUTPUT -p tcp --dport 25 -j DROP

# Get CA certs from cvmfs
rm -Rf /etc/grid-security
ln -sf /cvmfs/grid.cern.ch/etc/grid-security /etc/grid-security
export X509_CERT_DIR=/etc/grid-security/certificates
export SSL_CERT_DIR=/etc/grid-security/certificates

# These will be picked up by login etc shells
cat <<EOF > /etc/profile.d/grid-paths.sh
export X509_CERT_DIR=/etc/grid-security/certificates
export SSL_CERT_DIR=/etc/grid-security/certificates
export X509_VOMS_DIR=/etc/grid-security/vomsdir
EOF

# Swap as little as possible
sysctl vm.swappiness=1
       
# Don't want to be doing this at 4 or 5am every day!
rm -f /etc/cron.daily/mlocate.cron

# Log proxies used for cvmfs
for i in /cvmfs/*
do
  /bin/attr -g proxy $i
done

# Do DIRAC setup then run the DIRAC pilot
/usr/bin/sudo -i -n -u lhcb /home/lhcb/yandex-wn-dirac-setup

( /usr/bin/sudo -i -n -u lhcb /home/lhcb/yandex-wn-dirac-run slot1 ) >/var/log/yandex-wn-dirac-run.slot1.log 2>&1 &
( /usr/bin/sudo -i -n -u lhcb /home/lhcb/yandex-wn-dirac-run slot2 ) >/var/log/yandex-wn-dirac-run.slot2.log 2>&1 &

# Wait until both subprocesses are finished
wait

# Delete this VM, to prevent recycling
yc compute instance delete \
  --cloud-id b1g54dbp1scvqlrhgdns \
  --folder-id b1g6qvo98t320vf133hm \
  --token `cat /root/yandex-oauth.txt` \
  --name `hostname | cut -f1 -d.`

# We should never get here but do a conventional shutdown if we do
/sbin/shutdown -h now
sleep 60

# If that fails, do an instant reboot
echo o > /proc/sysrq-trigger

) >/var/log/yandex-wn-setup.log 2>&1
