#!/bin/sh -x
#
# Runs as dirac. Sets up to run dirac-pilot.py
#

date 
export HOME=/home/dirac
export HOST=`/bin/hostname`

DIRAC_SITE=CLOUD.YANDEX.ru
LHCBDIRAC_SETUP=LHCb-Production
CE_NAME=cloud.yandex.ru

for i in "$@"
do
case $i in
    --dirac-tmp=*)
    DIRAC_TMP="${i#*=}"
    shift
    ;;
    --dirac-site=*)
    DIRAC_SITE="${i#*=}"
    shift
    ;;
    --lhcb-setup=*)
    LHCBDIRAC_SETUP="${i#*=}"
    shift
    ;;
    --ce-name=*)
    CE_NAME="${i#*=}"
    shift
    ;;
    --vm-uuid=*)
    VM_UUID="${i#*=}"
    shift
    ;;
    --vmtype=*)
    VMTYPE="${i#*=}"
    shift
    ;;
    *)
    # unknown option
    ;;
esac
done

export LHCBDIRAC_TMPDIR=`mktemp -d -p $DIRAC_TMP`
cd $LHCBDIRAC_TMPDIR

# Default if not given explicitly
LHCBDIRAC_SETUP=${LHCBDIRAC_SETUP:-LHCb-Production}

# JOB_ID is used by when reporting LocalJobID by DIRAC watchdog
#export JOB_ID="$VMTYPE:$VM_UUID"

# We might be running from cvmfs or from /var/spool/checkout
export CONTEXTDIR=`readlink -f \`dirname $0\``

export TMPDIR=$LHCBDIRAC_TMPDIR
export EDG_WL_SCRATCH=$TMPDIR

# Needed to find software area
export VO_LHCB_SW_DIR=/cvmfs/lhcb.cern.ch

# Concatenated full certificate and key
export X509_USER_PROXY=$HOME/etc/grid-security/x509proxy.pem

python $HOME/production/Pilot3/dirac-pilot.py \
 --debug \
 --setup=$LHCBDIRAC_SETUP \
 --pilotCFGFile=$HOME/production/Pilot3/pilot.json \
 -l LHCb \
 -o lbRunOnly \
 --Name=$CE_NAME \
 --Queue=default \
 --MaxCycles=1 \
 --name=$DIRAC_SITE \
 --cert \
 --certLocation=$HOME/etc/grid-security \
 --commandExtensions LHCbPilot \
 --pythonVersion=3

