#!/bin/sh
#
# Must be run as root
#
# Get the system ready for a snapshot on the web dashboard
#
# You need to have these files in the lhcb $HOME directory first!
#   hostcert.pem 
#   hostkey.pem
#   oauth.txt
#   yandex-wn-setup
#   yandex-wn-dirac-setup
#   yandex-wn-dirac-run
# 

# Catch up as much as we can before the snapshot
yum -y update 

# Our script is run at the end of boot up
echo '/home/lhcb/yandex-wn-setup' >>/etc/rc.d/rc.local

sync
fsfreeze --freeze /
echo 'Ready for snapshot'
echo
echo 'Once snapshot is done, execute   fsfreeze --unfreeze /'
echo
