#!/bin/sh
#
# Must be run as root
#
# Get the system ready for a snapshot on the web dashboard
#
# You need to have these files in the lhcb $HOME directory first!
#   yandex-squid-setup
#   yandex-squid-template
# 

# Catch up as much as we can before the snapshot
yum -y update 

# Turn off IPv6
cat <<EOF >>/etc/sysctl.conf
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
EOF

# Our script is run at the end of boot up
echo '/home/lhcb/yandex-squid-setup' >>/etc/rc.d/rc.local

sync
fsfreeze --freeze /
echo 'Ready for snapshot'
echo
echo 'Once snapshot is done, execute   fsfreeze --unfreeze /'
echo
