#!/bin/sh
#
# Copy the files to a Yandex VM needed to make a snapshot
#
# On your computer, put the hostcert.pem/hostkey.pem and oauth.txt in the 
# current directory and clone the GitHub lhcb-yandex repo so it is a 
# subdirectory.
#
# oauth.txt contains the OAuth token 
#
# The single argument is the IP address of the VM you will snapshot
#
# Execute with  lhcb-yandex/yandex-wn-copy-snapshot-files xx.xx.xx.xx 
#

scp hostcert.pem \
    hostkey.pem  \
    yandex-oauth.txt \
    lhcb-yandex/yandex-wn-setup \
    lhcb-yandex/yandex-wn-dirac-run \
    lhcb-yandex/yandex-wn-dirac-setup \
    lhcb-yandex/yandex-wn-prepare-snapshot \
    lhcb@$1:
